spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.10:3306/mail_ums
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: mail-member
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000